// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");
                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, Author = "Robert C. Martin", Title = "Clean Code", Year = 2008 },
                        new { Id = 2, Author = "Hunt & Thomas", Title = "The Pragmatic Programmer", Year = 1999 },
                        new { Id = 3, Author = "Gang of Four", Title = "Design Patterns", Year = 1994 },
                        new { Id = 4, Author = "Martin Fowler", Title = "Refactoring", Year = 1999 },
                        new { Id = 5, Author = "Eric Evans", Title = "Domain-Driven Design", Year = 2003 });
                });

            modelBuilder.Entity("Data.LibraryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId").HasColumnType("int");
                    b.Property<DateTime>("Date").HasColumnType("datetime2");
                    b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<int>("UserId").HasColumnType("int");

                    b.HasKey("Id");
                    b.HasIndex("BookId");
                    b.HasIndex("UserId");
                    b.ToTable("Events");
                });

            modelBuilder.Entity("Data.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId").HasColumnType("int");
                    b.Property<bool>("IsAvailable").HasColumnType("bit");

                    b.HasKey("Id");
                    b.HasIndex("BookId").IsUnique();
                    b.ToTable("States");

                    b.HasData(
                        new { Id = 1, BookId = 1, IsAvailable = true },
                        new { Id = 2, BookId = 2, IsAvailable = true },
                        new { Id = 3, BookId = 3, IsAvailable = true },
                        new { Id = 4, BookId = 4, IsAvailable = true },
                        new { Id = 5, BookId = 5, IsAvailable = true });
                });

            modelBuilder.Entity("Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");

                    b.HasKey("Id");
                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Email = "alice@library.com", Name = "Alice Smith" },
                        new { Id = 2, Email = "bob@library.com", Name = "Bob Jones" },
                        new { Id = 3, Email = "carol@library.com", Name = "Carol White" });
                });

            modelBuilder.Entity("Data.LibraryEvent", b =>
                {
                    b.HasOne("Data.Book", "Book")
                        .WithMany("Events")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.State", b =>
                {
                    b.HasOne("Data.Book", "Book")
                        .WithOne("State")
                        .HasForeignKey("Data.State", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Data.Book", b =>
                {
                    b.Navigation("Events");
                    b.Navigation("State");
                });

            modelBuilder.Entity("Data.User", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
